# tools/gen_cards.py — build the printable character-card sheet.
#
# Reads the authored card blocks in cards/characters.md and writes a
# self-contained print sheet to cards/characters.html (A4, 9 cards per page,
# 63 mm x 88 mm each). The plain-words stat effect and the +-x term are derived
# here from the tier, so every card is worded identically. Shared page/CSS/CLI
# live in tools/cardsheet.py.
#
# Usage:
#   python tools/gen_cards.py                    # regenerate cards/characters.html
#   python tools/gen_cards.py --variant female    # same cards, art from cards/art/characters/female
#   python tools/gen_cards.py --check             # exit 1 if the file is out of date
#   python tools/gen_cards.py --stdout            # print the HTML instead of writing it
import cardsheet
from cardsheet import MINUS, ROOT, die, esc

PROG = "gen_cards"
SRC = ROOT / "cards" / "characters.md"

VARIANTS = {
    None: ("characters", ROOT / "cards" / "characters.html", ""),
    "female": ("characters/female", ROOT / "cards" / "characters-female.html", " (Female Art)"),
}

VARIANT = cardsheet.variant_arg(PROG, set(VARIANTS))
ART_DECK, OUT, TITLE_SUFFIX = VARIANTS[VARIANT]

# (stat, tier) -> (plain-words effect, term shown in the chip)
# v2: all three stats are offensive and parallel — each buffs its own attack type.
EFFECTS = {
    ("Magic", "High"): ("Your magic attacks gain +x.", "+x"),
    ("Magic", "Average"): ("Your magic attacks are unchanged.", "0"),
    ("Magic", "Low"): (f"Your magic attacks take {MINUS}x.", f"{MINUS}x"),
    ("Strength", "High"): ("Your strength attacks gain +x.", "+x"),
    ("Strength", "Average"): ("Your strength attacks are unchanged.", "0"),
    ("Strength", "Low"): (f"Your strength attacks take {MINUS}x.", f"{MINUS}x"),
    ("Agility", "High"): ("Your agility attacks gain +x.", "+x"),
    ("Agility", "Average"): ("Your agility attacks are unchanged.", "0"),
    ("Agility", "Low"): (f"Your agility attacks take {MINUS}x.", f"{MINUS}x"),
}

STAT_ORDER = ("Magic", "Strength", "Agility")
REQUIRED = STAT_ORDER + ("Playstyle", "Flavour")


def render_card(card: dict, total: int) -> str:
    rows = []
    for stat in STAT_ORDER:
        tier = card["stats"][stat]
        effect, term = EFFECTS[(stat, tier)]
        term_cls = "term term-zero" if term == "0" else "term"
        rows.append(
            f'      <div class="row">\n'
            f'        <div class="line">'
            f'<span class="key">{stat}</span>'
            f'<span class="val">{tier.upper()}</span>'
            f'<span class="termwrap"><span class="{term_cls}">{esc(term)}</span></span></div>\n'
            f'        <div class="effect">{esc(effect)}</div>\n'
            f'      </div>'
        )
    return (
        f'    <div class="card">\n'
        + cardsheet.card_top(ART_DECK, card["num"], total, card["name"], PROG) + "\n"
        + "\n".join(rows) + "\n"
        f'      <p class="rule">{esc(card["playstyle"])}</p>\n'
        f'      <p class="flavour">{esc(card["flavour"])}</p>\n'
        f'    </div>'
    )


def build_html(blocks: list[dict]) -> str:
    cards = []
    for b in blocks:
        f = b["fields"]
        missing = [k for k in REQUIRED if k not in f]
        if missing:
            die(PROG, f"card {b['num']} ({b['name']}) is missing: {', '.join(missing)}")
        for stat in STAT_ORDER:
            if (stat, f[stat]) not in EFFECTS:
                die(PROG, f"card {b['num']} ({b['name']}): unknown {stat} tier {f[stat]!r} "
                          f"(expected High, Average or Low)")
        cards.append({
            "num": b["num"], "name": b["name"],
            "stats": {s: f[s] for s in STAT_ORDER},
            "playstyle": f["Playstyle"], "flavour": f["Flavour"],
        })
    total = len(cards)
    body = "\n".join(render_card(c, total) for c in cards)
    variant_note = (
        f" Art variant: <code>{VARIANT}</code> (from <code>cards/art/{ART_DECK}/</code>)."
        if VARIANT else ""
    )
    hint = (
        "Generated by <code>tools/gen_cards.py"
        + (f" --variant {VARIANT}" if VARIANT else "") + "</code> from "
        "<code>cards/characters.md</code> — do not edit by hand." + variant_note + " "
        "Print to PDF (A4, 100% scale, margins from the file) for a cut-apart deck; "
        "reprint the sheet once per copy you need."
    )
    return cardsheet.document(
        f"Algebra Monster Battle — Character Cards{TITLE_SUFFIX}", "", hint, body
    )


if __name__ == "__main__":
    cardsheet.run(PROG, SRC, OUT, build_html)
