# tools/gen_cards.py — build the printable character-card sheet.
#
# Reads the authored card blocks in cards/characters.md and writes a
# self-contained print sheet to cards/characters.html (A4, 9 cards per page,
# 63 mm x 88 mm each). The plain-words stat effect and the +-x term are derived
# here from the tier, so every card is worded identically. Shared page/CSS/CLI
# live in tools/cardsheet.py.
#
# Usage:
#   python tools/gen_cards.py            # regenerate cards/characters.html
#   python tools/gen_cards.py --check    # exit 1 if the file is out of date
#   python tools/gen_cards.py --stdout   # print the HTML instead of writing it
import cardsheet
from cardsheet import MINUS, ROOT, die, esc

PROG = "gen_cards"
SRC = ROOT / "cards" / "characters.md"
OUT = ROOT / "cards" / "characters.html"

# (stat, tier) -> (plain-words effect, term shown in the chip)
EFFECTS = {
    ("Magic", "High"): ("Your magic attacks gain +x.", "+x"),
    ("Magic", "Average"): ("Your magic attacks are unchanged.", "0"),
    ("Magic", "Low"): (f"Your magic attacks take {MINUS}x.", f"{MINUS}x"),
    ("Agility", "High"): ("Your agility attacks gain +x.", "+x"),
    ("Agility", "Average"): ("Your agility attacks are unchanged.", "0"),
    ("Agility", "Low"): (f"Your agility attacks take {MINUS}x.", f"{MINUS}x"),
    ("Strength", "High"): (f"Enemy attacks against you take {MINUS}x.", f"{MINUS}x"),
    ("Strength", "Average"): ("Enemy attacks against you are unchanged.", "0"),
    ("Strength", "Low"): ("Enemy attacks against you gain +x.", "+x"),
}

STAT_ORDER = ("Magic", "Strength", "Agility")
REQUIRED = STAT_ORDER + ("Playstyle", "Flavour")


def render_card(card: dict, total: int) -> str:
    rows = []
    for stat in STAT_ORDER:
        tier = card["stats"][stat]
        effect, term = EFFECTS[(stat, tier)]
        # Strength is defensive and its sign is inverted vs Magic/Agility
        # (HIGH gives the *attacker* -x). Flag the row so students read it as
        # "the enemy's term", not their own: tinted row, "vs you" label, red term.
        is_def = stat == "Strength"
        row_cls = "row row-def" if is_def else "row"
        term_cls = "term"
        if term == "0":
            term_cls += " term-zero"
        elif is_def:
            term_cls += " term-def"
        prefix = '<span class="vsyou">vs you</span>' if is_def else ""
        val = f"{tier.upper()} <span class=\"deftag\">defence</span>" if is_def else tier.upper()
        rows.append(
            f'      <div class="{row_cls}">\n'
            f'        <div class="line">'
            f'<span class="key">{stat}</span>'
            f'<span class="val">{val}</span>'
            f'<span class="termwrap">{prefix}<span class="{term_cls}">{esc(term)}</span></span></div>\n'
            f'        <div class="effect">{esc(effect)}</div>\n'
            f'      </div>'
        )
    return (
        f'    <div class="card">\n'
        + cardsheet.card_top("characters", card["num"], total, card["name"], PROG) + "\n"
        + "\n".join(rows) + "\n"
        f'      <p class="rule">{esc(card["playstyle"])}</p>\n'
        f'      <p class="flavour">{esc(card["flavour"])}</p>\n'
        f'    </div>'
    )


def build_html(blocks: list[dict]) -> str:
    cards = []
    for b in blocks:
        f = b["fields"]
        missing = [k for k in REQUIRED if k not in f]
        if missing:
            die(PROG, f"card {b['num']} ({b['name']}) is missing: {', '.join(missing)}")
        for stat in STAT_ORDER:
            if (stat, f[stat]) not in EFFECTS:
                die(PROG, f"card {b['num']} ({b['name']}): unknown {stat} tier {f[stat]!r} "
                          f"(expected High, Average or Low)")
        cards.append({
            "num": b["num"], "name": b["name"],
            "stats": {s: f[s] for s in STAT_ORDER},
            "playstyle": f["Playstyle"], "flavour": f["Flavour"],
        })
    total = len(cards)
    body = "\n".join(render_card(c, total) for c in cards)
    hint = (
        "Generated by <code>tools/gen_cards.py</code> from "
        "<code>cards/characters.md</code> — do not edit by hand. "
        "Print to PDF (A4, 100% scale, margins from the file) for a cut-apart deck; "
        "reprint the sheet once per copy you need."
    )
    return cardsheet.document("Algebra Monster Battle — Character Cards", "", hint, body)


if __name__ == "__main__":
    cardsheet.run(PROG, SRC, OUT, build_html)
